import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../database/local_database.dart';

class ClinicalPdfGenerator {
  pw.Widget _header(Patient patient, String title) => pw.Column(
    crossAxisAlignment: pw.CrossAxisAlignment.start,
    children: [
      pw.Text(
        'Indira Gandhi Institute of Medical Sciences, Patna',
        style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold),
      ),
      pw.Text(title, style: pw.TextStyle(fontSize: 14)),
      pw.SizedBox(height: 6),
      pw.Text(
        'Patient: ${patient.fullName}    Registration: ${patient.hospitalRegNo}',
      ),
      pw.Text(
        'Bed: ${patient.metadata}    Date: ${DateTime.now().toIso8601String().split('T').first}',
      ),
      pw.Align(
        alignment: pw.Alignment.centerRight,
        child: pw.Text(
          'Generated by Clinical CDSS',
          style: const pw.TextStyle(color: PdfColors.grey),
        ),
      ),
      pw.Divider(),
    ],
  );

  pw.Widget _table(List<List<String>> rows) => pw.TableHelper.fromTextArray(
    headers: rows.isEmpty ? const [] : rows.first,
    data: rows.length <= 1 ? const [] : rows.sublist(1),
    border: pw.TableBorder.all(color: PdfColors.grey),
    cellStyle: const pw.TextStyle(fontSize: 9),
  );

  Future<List<int>> generateAdmissionNote(
    Patient patient,
    List<PatientProblem> problems,
    List<ClinicalEncounter> vitals,
    List<ClinicalAction> plan,
  ) => _document(_header(patient, 'Admission Note'), [
    pw.Text('Problems', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
    pw.Bullet(
      text: problems.map((p) => '${p.problemName} (${p.status})').join(', '),
    ),
    _table([
      ['Date', 'SBP/DBP', 'Pulse'],
      ...vitals.map(
        (v) => [
          v.occurredAt.toIso8601String(),
          '${v.sbp ?? '-'} / ${v.dbp ?? '-'}',
          '${v.pulse ?? '-'}',
        ],
      ),
    ]),
    pw.Text('Plan: ${plan.map((a) => a.description).join('; ')}'),
  ]);

  Future<List<int>> generateProgressNote(
    Patient patient,
    ClinicalEncounter latestVitals,
    String aiSummary,
    List<ClinicalAction> newOrders,
  ) => _document(_header(patient, 'Progress Note'), [
    pw.Text(
      'Vitals: ${latestVitals.sbp ?? '-'} / ${latestVitals.dbp ?? '-'} mmHg   PR ${latestVitals.pulse ?? '-'}',
    ),
    pw.SizedBox(height: 8),
    pw.Text(aiSummary),
    pw.SizedBox(height: 8),
    pw.Text('Orders: ${newOrders.map((a) => a.description).join('; ')}'),
  ]);

  Future<List<int>> generateDischargeSummary(
    Patient patient,
    List<PatientProblem> resolvedProblems,
    List<ClinicalAction> dischargeMeds,
    String followUp,
    {List<String> icd11Codes = const [], List<String> pmJayCodes = const []}
  ) => _document(_header(patient, 'Discharge Summary'), [
    pw.Text(
      'Resolved Problems: ${resolvedProblems.map((p) => p.problemName).join(', ')}',
    ),
    _table([
      ['Medication', 'Type'],
      ...dischargeMeds.map((a) => [a.description, a.actionType]),
    ]),
    if (icd11Codes.isNotEmpty) ...[
      pw.SizedBox(height: 10),
      pw.Text('ICD-11 codes: ${icd11Codes.join(', ')}'),
    ],
    if (pmJayCodes.isNotEmpty)
      pw.Text('PM-JAY package codes: ${pmJayCodes.join(', ')}'),
    pw.Text('Follow-up: $followUp'),
  ]);

  Future<List<int>> generateOpdPrescription(
    Patient patient,
    PatientProblem chiefComplaint,
    List<ClinicalAction> advisedMeds,
  ) => _document(_header(patient, 'OPD Prescription'), [
    pw.Text('Chief complaint: ${chiefComplaint.problemName}'),
    _table([
      ['Medicine', 'Instructions'],
      ...advisedMeds.map((a) => [a.description, a.actionType]),
    ]),
  ]);

  Future<List<int>> _document(pw.Widget header, List<pw.Widget> body) async {
    final document = pw.Document();
    document.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        header: (_) => header,
        build: (_) => body,
      ),
    );
    return document.save();
  }
}
