-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.patients (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  owner_id uuid NOT NULL DEFAULT auth.uid(),
  hospital_reg_no text CHECK (length(btrim(hospital_reg_no)) > 0),
  full_name text NOT NULL CHECK (length(btrim(full_name)) > 0),
  date_of_birth date,
  sex text CHECK (sex IS NULL OR (sex = ANY (ARRAY['female'::text, 'male'::text, 'intersex'::text, 'unknown'::text]))),
  phone text,
  diagnosis text,
  current_department text NOT NULL DEFAULT 'Surgery'::text CHECK (current_department = ANY (ARRAY['Medicine'::text, 'OBGYN'::text, 'Pediatrics'::text, 'Surgery'::text, 'Psychiatry'::text, 'Emergency'::text, 'Other'::text])),
  surgery_type text,
  complications text,
  admission_date timestamp with time zone,
  discharge_date timestamp with time zone,
  is_active boolean NOT NULL DEFAULT true,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  last_synced_at timestamp with time zone,
  gender text,
  residence text,
  occupation text,
  height_cm real,
  weight_kg real,
  alternate_phone text,
  mrn text,
  hospital_id uuid,
  CONSTRAINT patients_pkey PRIMARY KEY (id),
  CONSTRAINT patients_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id),
  CONSTRAINT patients_hospital_id_fkey FOREIGN KEY (hospital_id) REFERENCES public.hospitals(id)
);
CREATE TABLE public.clinical_encounters (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  owner_id uuid NOT NULL DEFAULT auth.uid(),
  patient_id uuid NOT NULL,
  encounter_type text NOT NULL DEFAULT 'Ward Round'::text,
  occurred_at timestamp with time zone NOT NULL DEFAULT now(),
  sbp smallint CHECK (sbp IS NULL OR sbp >= 20 AND sbp <= 300),
  dbp smallint CHECK (dbp IS NULL OR dbp >= 10 AND dbp <= 250),
  pulse smallint CHECK (pulse IS NULL OR pulse >= 1 AND pulse <= 300),
  temperature_c numeric CHECK (temperature_c IS NULL OR temperature_c >= 25::numeric AND temperature_c <= 50::numeric),
  respiratory_rate smallint CHECK (respiratory_rate IS NULL OR respiratory_rate >= 1 AND respiratory_rate <= 100),
  spo2 smallint CHECK (spo2 IS NULL OR spo2 >= 0 AND spo2 <= 100),
  map numeric,
  chief_complaint text,
  consultant_advice text,
  note text,
  dynamic_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  last_synced_at timestamp with time zone,
  hospital_id uuid,
  care_setting text NOT NULL DEFAULT 'OPD'::text,
  is_draft boolean NOT NULL DEFAULT false,
  department text,
  ward_name text,
  bed_number text,
  clinical_diagnosis text,
  icd11_code text,
  disposition text,
  chief_complaints text,
  history_of_present_illness text,
  past_history text,
  drug_and_allergy_history text,
  personal_and_social_history text,
  examination_findings text,
  clinical_assessment text,
  image_path text,
  ai_summary text,
  pediatric_history text NOT NULL DEFAULT '{}'::text,
  ob_gy_history text NOT NULL DEFAULT '{}'::text,
  CONSTRAINT clinical_encounters_pkey PRIMARY KEY (id),
  CONSTRAINT clinical_encounters_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT clinical_encounters_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id),
  CONSTRAINT clinical_encounters_hospital_id_fkey FOREIGN KEY (hospital_id) REFERENCES public.hospitals(id)
);
CREATE TABLE public.investigation_tracker (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  owner_id uuid NOT NULL DEFAULT auth.uid(),
  patient_id uuid NOT NULL,
  test_name text NOT NULL CHECK (length(btrim(test_name)) > 0),
  test_code text,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'sample_sent'::text, 'result_received'::text, 'cancelled'::text])),
  ordered_at timestamp with time zone NOT NULL DEFAULT now(),
  sample_sent_at timestamp with time zone,
  result_received_at timestamp with time zone,
  result_value text,
  result_unit text,
  reference_range text,
  organism text,
  sensitive_antibiotics ARRAY NOT NULL DEFAULT '{}'::text[],
  resistant_antibiotics ARRAY NOT NULL DEFAULT '{}'::text[],
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  last_synced_at timestamp with time zone,
  CONSTRAINT investigation_tracker_pkey PRIMARY KEY (id),
  CONSTRAINT investigation_tracker_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id),
  CONSTRAINT investigation_tracker_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id)
);
CREATE TABLE public.drug_master (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  owner_id uuid NOT NULL DEFAULT auth.uid(),
  generic_name text NOT NULL CHECK (length(btrim(generic_name)) > 0),
  brand_name text,
  strength text,
  dosage_form text,
  route text,
  category text,
  searchable_text text DEFAULT lower(((((((((((COALESCE(generic_name, ''::text) || ' '::text) || COALESCE(brand_name, ''::text)) || ' '::text) || COALESCE(strength, ''::text)) || ' '::text) || COALESCE(dosage_form, ''::text)) || ' '::text) || COALESCE(route, ''::text)) || ' '::text) || COALESCE(category, ''::text))),
  is_active boolean NOT NULL DEFAULT true,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  last_synced_at timestamp with time zone,
  CONSTRAINT drug_master_pkey PRIMARY KEY (id),
  CONSTRAINT drug_master_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id)
);
CREATE TABLE public.personal_wiki (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  owner_id uuid NOT NULL DEFAULT auth.uid(),
  topic text NOT NULL CHECK (length(btrim(topic)) > 0),
  markdown_content text NOT NULL DEFAULT ''::text,
  tags ARRAY NOT NULL DEFAULT '{}'::text[],
  department_relevance ARRAY NOT NULL DEFAULT '{}'::text[],
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  last_synced_at timestamp with time zone,
  CONSTRAINT personal_wiki_pkey PRIMARY KEY (id),
  CONSTRAINT personal_wiki_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id)
);
CREATE TABLE public.sync_queue (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  owner_id uuid NOT NULL DEFAULT auth.uid(),
  entity_type text NOT NULL CHECK (entity_type = ANY (ARRAY['patients'::text, 'clinical_encounters'::text, 'investigation_tracker'::text, 'drug_master'::text, 'personal_wiki'::text])),
  entity_id uuid NOT NULL,
  operation text NOT NULL CHECK (operation = ANY (ARRAY['insert'::text, 'update'::text, 'delete'::text])),
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  client_updated_at timestamp with time zone NOT NULL DEFAULT now(),
  attempts integer NOT NULL DEFAULT 0 CHECK (attempts >= 0),
  next_attempt_at timestamp with time zone NOT NULL DEFAULT now(),
  last_error text,
  processed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  last_synced_at timestamp with time zone,
  CONSTRAINT sync_queue_pkey PRIMARY KEY (id),
  CONSTRAINT sync_queue_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id)
);
CREATE TABLE public.patient_problems (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  owner_id uuid NOT NULL DEFAULT auth.uid(),
  patient_id uuid NOT NULL,
  problem_name text NOT NULL,
  status text NOT NULL DEFAULT 'Active'::text CHECK (status = ANY (ARRAY['Active'::text, 'Resolved'::text, 'Chronic'::text])),
  onset_date date,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  last_synced_at timestamp with time zone,
  CONSTRAINT patient_problems_pkey PRIMARY KEY (id),
  CONSTRAINT patient_problems_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id),
  CONSTRAINT patient_problems_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id)
);
CREATE TABLE public.clinical_actions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  owner_id uuid NOT NULL DEFAULT auth.uid(),
  patient_id uuid NOT NULL,
  problem_id uuid NOT NULL,
  action_type text NOT NULL CHECK (action_type = ANY (ARRAY['Medication'::text, 'Procedure'::text, 'Investigation'::text, 'Consultation'::text])),
  description text NOT NULL,
  occurred_at timestamp with time zone NOT NULL DEFAULT now(),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  last_synced_at timestamp with time zone,
  CONSTRAINT clinical_actions_pkey PRIMARY KEY (id),
  CONSTRAINT clinical_actions_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id),
  CONSTRAINT clinical_actions_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT clinical_actions_problem_id_fkey FOREIGN KEY (problem_id) REFERENCES public.patient_problems(id)
);
CREATE TABLE public.clinical_outcomes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  owner_id uuid NOT NULL DEFAULT auth.uid(),
  problem_id uuid NOT NULL,
  metric_name text NOT NULL,
  metric_value numeric NOT NULL,
  metric_unit text,
  treatment_method text,
  measured_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  last_synced_at timestamp with time zone,
  CONSTRAINT clinical_outcomes_pkey PRIMARY KEY (id),
  CONSTRAINT clinical_outcomes_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id),
  CONSTRAINT clinical_outcomes_problem_id_fkey FOREIGN KEY (problem_id) REFERENCES public.patient_problems(id)
);
CREATE TABLE public.cdss_rules (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  owner_id uuid NOT NULL DEFAULT auth.uid(),
  target_problem text NOT NULL,
  trigger_condition text NOT NULL,
  suggested_action text NOT NULL,
  evidence_source text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  last_synced_at timestamp with time zone,
  CONSTRAINT cdss_rules_pkey PRIMARY KEY (id),
  CONSTRAINT cdss_rules_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id)
);
CREATE TABLE public.hospitals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  short_name text,
  address text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT hospitals_pkey PRIMARY KEY (id)
);
CREATE TABLE public.wards (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  hospital_id uuid,
  department text,
  ward_name text NOT NULL,
  bed_count integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT wards_pkey PRIMARY KEY (id),
  CONSTRAINT wards_hospital_id_fkey FOREIGN KEY (hospital_id) REFERENCES public.hospitals(id)
);
CREATE TABLE public.patient_hospital_identifiers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  patient_id uuid NOT NULL,
  hospital_id uuid NOT NULL,
  hospital_reg_no text,
  is_primary boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  mrn text,
  identifier_type text NOT NULL DEFAULT 'MRN'::text,
  CONSTRAINT patient_hospital_identifiers_pkey PRIMARY KEY (id),
  CONSTRAINT patient_hospital_identifiers_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT patient_hospital_identifiers_hospital_id_fkey FOREIGN KEY (hospital_id) REFERENCES public.hospitals(id)
);
CREATE TABLE public.problem_progress_snapshots (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  problem_id uuid NOT NULL,
  encounter_id uuid NOT NULL,
  patient_id uuid NOT NULL,
  status_snapshot text NOT NULL,
  clinical_course_note text NOT NULL,
  recorded_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  owner_id uuid NOT NULL DEFAULT auth.uid(),
  CONSTRAINT problem_progress_snapshots_pkey PRIMARY KEY (id),
  CONSTRAINT problem_progress_snapshots_problem_id_fkey FOREIGN KEY (problem_id) REFERENCES public.patient_problems(id),
  CONSTRAINT problem_progress_snapshots_encounter_id_fkey FOREIGN KEY (encounter_id) REFERENCES public.clinical_encounters(id),
  CONSTRAINT problem_progress_snapshots_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id)
);
CREATE TABLE public.clinical_interventions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  patient_id uuid NOT NULL,
  encounter_id uuid NOT NULL,
  problem_id uuid,
  procedure_name text NOT NULL,
  procedure_code text,
  coding_system text,
  anatomical_site text,
  intervention_role text NOT NULL DEFAULT 'Therapeutic'::text,
  operative_findings text,
  performed_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  performed_by text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  owner_id uuid NOT NULL DEFAULT auth.uid(),
  CONSTRAINT clinical_interventions_pkey PRIMARY KEY (id),
  CONSTRAINT clinical_interventions_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT clinical_interventions_encounter_id_fkey FOREIGN KEY (encounter_id) REFERENCES public.clinical_encounters(id),
  CONSTRAINT clinical_interventions_problem_id_fkey FOREIGN KEY (problem_id) REFERENCES public.patient_problems(id)
);
CREATE TABLE public.clinical_outcome_metrics (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  patient_id uuid NOT NULL,
  problem_id uuid NOT NULL,
  encounter_id uuid,
  metric_name text NOT NULL,
  metric_value real NOT NULL,
  metric_unit text,
  qualifying_note text,
  measured_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  owner_id uuid NOT NULL DEFAULT auth.uid(),
  CONSTRAINT clinical_outcome_metrics_pkey PRIMARY KEY (id),
  CONSTRAINT clinical_outcome_metrics_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT clinical_outcome_metrics_problem_id_fkey FOREIGN KEY (problem_id) REFERENCES public.patient_problems(id),
  CONSTRAINT clinical_outcome_metrics_encounter_id_fkey FOREIGN KEY (encounter_id) REFERENCES public.clinical_encounters(id)
);
CREATE TABLE public.prescription_orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  patient_id uuid NOT NULL,
  encounter_id uuid NOT NULL,
  problem_id uuid,
  drug_name text NOT NULL,
  dose_strength text,
  dosage_form text,
  route text,
  frequency text,
  duration text,
  diluent_and_rate text,
  special_instructions text,
  is_active boolean NOT NULL DEFAULT true,
  ordered_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  owner_id uuid NOT NULL DEFAULT auth.uid(),
  CONSTRAINT prescription_orders_pkey PRIMARY KEY (id),
  CONSTRAINT prescription_orders_problem_id_fkey FOREIGN KEY (problem_id) REFERENCES public.patient_problems(id),
  CONSTRAINT prescription_orders_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT prescription_orders_encounter_id_fkey FOREIGN KEY (encounter_id) REFERENCES public.clinical_encounters(id)
);
CREATE TABLE public.investigation_orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  patient_id uuid NOT NULL,
  encounter_id uuid,
  problem_id uuid,
  test_name text NOT NULL,
  test_code text,
  clinical_indication text,
  status text NOT NULL DEFAULT 'ordered'::text,
  ordered_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  sample_sent_at timestamp with time zone,
  result_received_at timestamp with time zone,
  owner_id text NOT NULL DEFAULT 'local-practitioner'::text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT investigation_orders_pkey PRIMARY KEY (id),
  CONSTRAINT investigation_orders_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT investigation_orders_encounter_id_fkey FOREIGN KEY (encounter_id) REFERENCES public.clinical_encounters(id),
  CONSTRAINT investigation_orders_problem_id_fkey FOREIGN KEY (problem_id) REFERENCES public.patient_problems(id)
);
CREATE TABLE public.investigation_results (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid,
  patient_id uuid NOT NULL,
  test_name text NOT NULL,
  numeric_value real,
  text_value text,
  unit text,
  reference_range text,
  is_abnormal boolean NOT NULL DEFAULT false,
  antibiogram_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  result_date timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT investigation_results_pkey PRIMARY KEY (id),
  CONSTRAINT investigation_results_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.investigation_orders(id),
  CONSTRAINT investigation_results_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id)
);
CREATE TABLE public.learned_catalog (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  category text NOT NULL,
  term text NOT NULL,
  frequency integer NOT NULL DEFAULT 1,
  last_used_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT learned_catalog_pkey PRIMARY KEY (id)
);
CREATE TABLE public.admissions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  owner_id uuid NOT NULL DEFAULT auth.uid(),
  patient_id uuid NOT NULL,
  hospital_id uuid NOT NULL,
  ward_name text,
  bed_number text,
  admission_time timestamp with time zone NOT NULL DEFAULT now(),
  discharge_time timestamp with time zone,
  status text NOT NULL DEFAULT 'active'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  last_synced_at timestamp with time zone,
  CONSTRAINT admissions_pkey PRIMARY KEY (id),
  CONSTRAINT admissions_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT admissions_hospital_id_fkey FOREIGN KEY (hospital_id) REFERENCES public.hospitals(id),
  CONSTRAINT admissions_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id)
);
CREATE TABLE public.document_registries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  owner_id uuid NOT NULL DEFAULT auth.uid(),
  patient_id uuid NOT NULL,
  document_category text NOT NULL,
  image_path text NOT NULL,
  raw_ocr_transcript text NOT NULL DEFAULT ''::text,
  confidence_score real NOT NULL DEFAULT 0.0,
  documented_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  last_synced_at timestamp with time zone,
  image_hash text,
  clincom_json text,
  CONSTRAINT document_registries_pkey PRIMARY KEY (id),
  CONSTRAINT document_registries_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT document_registries_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id)
);
CREATE TABLE public.clinical_observations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  owner_id uuid NOT NULL DEFAULT auth.uid(),
  patient_id uuid NOT NULL,
  document_id uuid,
  observation_category text NOT NULL,
  code text NOT NULL,
  display_name text NOT NULL,
  numeric_value real,
  text_value text,
  unit text,
  reference_low real,
  reference_high real,
  is_abnormal boolean NOT NULL DEFAULT false,
  recorded_at timestamp with time zone NOT NULL,
  corroboration_note text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  last_synced_at timestamp with time zone,
  CONSTRAINT clinical_observations_pkey PRIMARY KEY (id),
  CONSTRAINT clinical_observations_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT clinical_observations_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.document_registries(id),
  CONSTRAINT clinical_observations_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id)
);
CREATE TABLE public.clinical_drugs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  owner_id text NOT NULL DEFAULT 'local-practitioner'::text,
  generic_name text NOT NULL,
  brand_name text,
  strength text,
  usage_frequency integer NOT NULL DEFAULT 0,
  associated_problems text NOT NULL DEFAULT '[]'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT clinical_drugs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.active_ingredients (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  molecule_code text NOT NULL,
  generic_name text NOT NULL,
  therapeutic_class text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT active_ingredients_pkey PRIMARY KEY (id)
);
CREATE TABLE public.indications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  molecule_code text NOT NULL,
  clinical_indication text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT indications_pkey PRIMARY KEY (id)
);
CREATE TABLE public.formulations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  molecule_code text NOT NULL,
  strength text,
  dosage_form text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT formulations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.brands (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  molecule_code text NOT NULL,
  brand_name text NOT NULL,
  manufacturer text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT brands_pkey PRIMARY KEY (id)
);
CREATE TABLE public.clinical_learning_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  encounter_id uuid,
  patient_id uuid NOT NULL,
  owner_id text NOT NULL DEFAULT 'local-practitioner'::text,
  diagnosis_confidence_score integer NOT NULL DEFAULT 5 CHECK (diagnosis_confidence_score >= 1 AND diagnosis_confidence_score <= 10),
  differential_diagnoses text NOT NULL DEFAULT ''::text,
  decision_rationale text NOT NULL DEFAULT ''::text,
  clinical_takeaway text NOT NULL DEFAULT ''::text,
  tags text NOT NULL DEFAULT '[]'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT clinical_learning_logs_pkey PRIMARY KEY (id),
  CONSTRAINT clinical_learning_logs_encounter_id_fkey FOREIGN KEY (encounter_id) REFERENCES public.clinical_encounters(id),
  CONSTRAINT clinical_learning_logs_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id)
);